### ISSUE TITLE
add a {pkgdown} GH action to build the docs on push to `main`

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/pacta.aggregate.loanbook.plots#63]
probably using this as a model https://github.com/r-lib/actions/blob/v2-branch/examples/pkgdown.yaml

**Comment by jdhoffa** [comment]
Closed by: https://github.com/RMI-PACTA/pacta.aggregate.loanbook.plots/pull/61

**Comment by jacobvjk** [comment]
indeed just merged this morning. closing the issue
