### ISSUE TITLE
vignettes do not show

### ISSUE THREAD

**Issue by jacobvjk** [RMI-PACTA/pacta.aggregate.loanbook.plots#93]

**Comment by jdhoffa** [comment]
I'll admit, my memory of how vignettes get added to `pkgdown` is a bit hazy, but I don't believe it happens automatically!

I would suggest using https://github.com/RMI-PACTA/r2dii.analysis as a basis, and seeing how the "Target Market Share" article is formatted, and making sure the config is all setup correctly.

**Comment by jacobvjk** [comment]
thing is it used to work when this package was public initially. but will take another look when I have the time

**Comment by jdhoffa** [comment]
Hmmm ok. Also happy to pair program this a bit and see if we can figure it out.

**Comment by jacobvjk** [comment]
it's more that I am a bit pressed for time on projects right now.. we can maybe check in early next week

**Comment by jdhoffa** [comment]
yup no rush/ worries
